version: '3.7'

services:
  currency-exchange:
    image: ankitsharma99/converter-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
     EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka


  naming-server:
    image: ankitsharma99/converter-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
networks:
  currency-network: